publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
backend:
  name: github
  base_url: https://github.io
  repo: wecitizens/electoral-gps-frontend
  branch: master-cms
collections:
  - name: "page" # Used in routes, e.g., /admin/collections/blog
    label: "page" # Used in the UI
    folder: "content/page" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Language", name: "language"}
      - {label: "Body", name: "body", widget: "markdown"}
